import { Header } from "@/components/Header";
import styles from "./page.module.css";
import "./globals.css";

export const metadata = {
  title: "Converter",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className={styles.container}>
          <Header />
          <main className={styles.main}>{children}</main>
        </div>
      </body>
    </html>
  );
}
